name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  id-token: write # Required for PyPI Trusted Publishing

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      !startsWith(github.event.workflow_run.head_commit.message, 'bump:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Commitizen
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - id: bump
        name: Bump version & generate changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # Do not stop the workflow if there are no commits to bump

      # If cz performed a bump (exit code 0), continue; otherwise, skip all remaining steps.
      - name: Setup Python
        if: steps.bump.outcome == 'success'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install project & build-​tools
        if: steps.bump.outcome == 'success'
        run: |
          pip install -e . 
          pip install pytest pytest-cov codecov build twine

      - name: Run tests & generate coverage report
        if: steps.bump.outcome == 'success'
        run: pytest --cov=giorgio --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        if: steps.bump.outcome == 'success'
        uses: codecov/codecov-action@v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

      - name: Build distribution
        if: steps.bump.outcome == 'success'
        run: python -m build --sdist --wheel

      - name: Publish to PyPI
        if: steps.bump.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1