name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: read
  id-token: write # Required for PyPI Trusted Publishing

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches the entire history and tags

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project & tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov codecov commitizen build twine

      - name: Run tests & generate coverage report
        run: pytest --cov=giorgio --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

      - id: bump
        name: Bump version & generate changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # Do not stop the workflow if there are no commits to bump

      - name: Build distribution
        if: steps.bump.outcome == 'success'
        run: python -m build --sdist --wheel

      - name: Publish to PyPI
        if: steps.bump.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
